version: '3'
services:
  ReactApp:
    image: 3.110.136.84:8082/react-login-app:Latest
    ports:
      - 3001:3000
  SpringBoot:
    image: 3.110.136.84:8082/mvn-hello-spring:6
    ports:
      - 8008:8088
