version: "3"
services:
  myreact:
    image: nginx:latest
    ports: 
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
    networks:
      - frontend
    deploy: 
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  frontend:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.0.37.0/24

